server:
  port: 8080
  forward-headers-strategy: framework  # 프록시 서버 뒤에서 실제 클라이언트 IP 추출

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springweb
    username: root
    password: 1234

cube-downloader:
  settings:
    bin: "C:/test/yt-dlp.exe"
    download-path: "Z:/"
  minio:
    server: "http://192.168.56.101:9000"
    user: devcube
    password: devcube1234
    bucket: test

logging:
  level:
    org.springframework: INFO # 프로젝트 전체 로그레벨 적용
    cubednloader: DEBUG # 특정 패키지 로그레벨 적용
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # 콘솔로그 출력 포맷 지정